### ISSUE TITLE
AIS Login shows both logged in and failed same time when retrying

### ISSUE THREAD

**Issue by Joshimello** [nthumodifications/courseweb#116]
**Describe the bug**
![opera_8WjSVI67O2](https://github.com/nthumodifications/courseweb/assets/74640729/b5cd3697-93f1-4656-8648-91e183fe68b2)

**To Reproduce**
AIS Login and wait

**Expected behavior**
show "logging in..." while retrying captcha
"failed" when fail and "connected" when ok

**Comment by ImJustChew** [comment]
needs to add additional states in AIS login logic
