### ISSUE TITLE
Page reloads twice on first load (or on all load?)

### ISSUE THREAD

**Issue by Joshimello** [nthumodifications/courseweb#119]
**Describe the bug**
Help/Tutorial modal is supposed to show on first load. The page loads the first time showing the modal (in light mode) but quickly reloads (in dark mode) and the modal no longer shows.

**To Reproduce**
Go incog mode, go to nthumods.com

**Expected behavior**
Page shouldn't load twice. Other than help/tutorial not showing issue, theme flashing is not optimal also.

**Additional context**
Bypass can be made, to always show the help page until the user actually dismisses it. (This will be done if double reload issue not found)

**Comment by Joshimello** [comment]
temp fix made for popup not showing
[23685cd](https://github.com/nthumodifications/courseweb/commit/23685cdbad1dc41b5417df3ed85dfbf5bef6a1fe)

**Comment by ImJustChew** [comment]
Investigating but unsure, might be something to do with top level components

**Comment by ImJustChew** [comment]
I think i might have found the culprit

https://github.com/nthumodifications/courseweb/blob/91754c8749044dd577988abfd5722bb3f6534be9/src/hooks/contexts/settings.tsx#L77

**Comment by Joshimello** [comment]
What

**Comment by ImJustChew** [comment]
MUI related, will close for migration to shadcn.
