### ISSUE TITLE
Improvements (Justin

### ISSUE THREAD

**Issue by Komeii** [nthumodifications/courseweb#132]
Weather
- [ ]    - Include wind factor
- [x]    - Hover data change to point form (easier to read
Courses
- [ ]    - Level can put a hover question mark to explain what is 1xxx etc 
- [ ]    - Add filter to say bachelor’s course/masters etc
- [x]    - Mentions 三選 or not? (some courses limit to who can choose at what time
- [x]       - Or you could just say remember go check original source
- [x]       - I think its nice if there was a reminder to say oh 三選 coming rmbr to apply
- [x]    - Search through time
Bus
- [x] Display time when bus arrives
- [x] Link your github in a more obvious place
 Friendly mode
- [ ]    - Anime girl flame
- [x]    - Diss school
Apps
- [ ]    - Explain what star does
- [ ]    - Rework starred products
- [ ]    - Add apps via today page
- [ ]    - Add star on the left side of app list
Timetable
- [ ]    - Add prof after choose class
- [x]    - Choose color for each class (or reorder classes if that sounds better)
- [x]    - Disclaimer for class
- [ ]       - Mention to check if 符合 department
- [x] - Bottom of page heart emoji change to <3
- [ ] - Add credits to where u steal
- [x] - Update footer socials
- [x]    - Emali
- [x]    - Github
- [x]    - I dont like footer remove footer please
- [x]    - Make socials more obvious
- [ ]       - Can add in settings directly?
- [ ]       - Add a contact us page
Make a for you page?
- [ ]    - Eg: when got rain then remind to bring umbrella out
- [ ]    - Or give a quick run down for your day
- [ ]    - Reminders?
- [ ]       - Meetings
- [ ]       - Appointments
- [ ]       - Documents to get etc
- [ ]    

 **Original Document**
https://docs.google.com/document/d/1z6Av1015hBKXkl3XAkkiHR2TDGzDnpbBE5noHerRbXA/edit?usp=sharing

**Comment by ImJustChew** [comment]
Bump
