### ISSUE TITLE
Timetable screenshot has weird shadows.

### ISSUE THREAD

**Issue by ImJustChew** [nthumodifications/courseweb#160]
**Describe the bug**
"下載課表時圖片陰影有問題，應該是跑圖" 
"不像前幾天的下載圖檔（圖二）有完整課程名稱⋯⋯"

**To Reproduce**
1. Go to timetable, download.

**Expected behavior**
Clean Timetable
**Screenshots**
![timetable - 羅俊璋](https://github.com/nthumodifications/courseweb/assets/17233431/a403eb3d-b26b-496f-970c-7692fa355ce9)

**Comment by ImJustChew** [comment]
@Joshimello should we just remove shadows all together? would fix the problem entirely.

**Comment by Joshimello** [comment]
> @Joshimello should we just remove shadows all together? would fix the problem entirely.
sure why not
