### ISSUE TITLE
TSMC Building 站合并

### ISSUE THREAD

**Issue by ccwei-311** [nthumodifications/courseweb#17]
Tsmc building 應該要把上山，下山合併用起來比較舒服~

**Comment by ImJustChew** [comment]
那個站是分開的 因爲TSMC 那邊有兩個公車站，除非加一個Tab 換另一個站

類似：
![image](https://github.com/nthumodifications/courseweb/assets/17233431/70926fc3-0426-42cb-8b21-9307643c9097)

還是有什麽建議嗎
