### ISSUE TITLE
加成績查詢 UI

### ISSUE THREAD

**Issue by ImJustChew** [nthumodifications/courseweb#175]

**Comment by sandy891209** [comment]
@ImJustChew How many breakpoints should I design? (pc, tablet, mobile?) I need a pixel number. Thanks!

**Comment by ImJustChew** [comment]
We use TailwindCSS default breakpoints
'sm': '640px',
'md': '768px',
'lg': '1024px',

We usually design only for mobile and PC, below 768px is mobile.

**Comment by ImJustChew** [comment]
Additionally there's also 
'xl': '1280px',
'2xl': '1536px',

**Comment by sandy891209** [comment]
@ImJustChew I finished ui design. If u have any questions u can comment on Figma.
