### ISSUE TITLE
shops: fetch shops data from nthusa/api

### ISSUE THREAD

**Issue by Joshimello** [nthumodifications/courseweb#219]
Shops data should regularly fetch from API since data changes every once in a while.
Continue from #130 

Issues to solve:
- [ ] Data is does not have consistent format.

**Comment by ImJustChew** [comment]
Can we use ChatGPT API or something automated to read the data and output
the result?

**Comment by ImJustChew** [comment]
But because the dates are also modified by staff who don't really have the idea of formatting, there's definetly some issues that might arise.

**Comment by ImJustChew** [comment]
This is high priority now since the feature is now public, or at least the data must be accurate.
