### ISSUE TITLE
Link code from my prev nthumods-like flutter project

### ISSUE THREAD

**Issue by waltsai2483** [nthumodifications/courseweb#233]
Repo: https://github.com/waltsai2483/aip

Run on Android & iOS, written by Dart. 
Finished features:
- Bulletins at lib/api/notification_helper.dart
- City/Intercity Bus tracking at lib/api/bus_helper.dart

Supported bus id and notification types are stored in another repo in json format.

**Comment by ImJustChew** [comment]
What features would you like to migrate from your previous app? Can some of those data be obtained on NTHUSA/api?

Please split them into individual Issues for each feat/improvement. Thanks ^^
