### ISSUE TITLE
Shops: fetch issue & shops displaying data incorrectly

### ISSUE THREAD

**Issue by Joshimello** [nthumodifications/courseweb#291]
![Screenshot_2024-04-26-13-23-49-205_com.android.chrome.jpg](https://github.com/nthumodifications/courseweb/assets/74640729/612c10fb-fb6f-4010-a309-aad97c2152f2)

**Comment by ImJustChew** [comment]
https://api.nthusa.tw/dining/ is failing, tracking issue on https://github.com/NTHU-SA/NTHU-Data-API/issues/96

**Comment by ImJustChew** [comment]
API is now back up, but data parsing is wrong.

**Comment by Joshimello** [comment]
#315
