### ISSUE TITLE
Feature request for level (grade) selecting

### ISSUE THREAD

**Issue by smolsquirrel936** [nthumodifications/courseweb#428]
我看到 [NUSMods](https://nusmods.com/) 有年級選擇。希望可以增加這個功能，讓使用者可以一次篩選出多個年級的課程，謝謝！

**Comment by ImJustChew** [comment]
![image](https://github.com/user-attachments/assets/62b81267-36d1-4306-bad1-aabc7ecb8ae1)
類似 NUSMods 用課號篩選嗎，因爲清大的課號沒有跟著實際年級。

**Comment by smolsquirrel936** [comment]
對，因為現在只能輸入數字來搜尋，例如輸入 5 可以搜尋到 5XXX 的課，但不能一次搜尋 5,6,7 這樣子
