### ISSUE TITLE
Courses filter by time refining

### ISSUE THREAD

**Issue by Joshimello** [nthumodifications/courseweb#47]
**Is your feature request related to a problem? Please describe.**
- Currently, time filters for classes 'within' selected time
- Time filter should not include classes with no time specified

**Describe the solution you'd like**
- Add checkbox to show courses with no specific time
- Add checkbox to swap between results that are (within selected / includes selected)

![opera_O58Rf3rVGA](https://github.com/nthumodifications/courseweb/assets/74640729/5e664027-90e8-48d3-9bee-4278ffb5ed77)

**Comment by ImJustChew** [comment]
I doubt ppl have the need for filtering courses with no time, so we'll skip that for now.
