### ISSUE TITLE
修課同學搜尋

### ISSUE THREAD

**Issue by ImJustChew** [nthumodifications/courseweb#61]
**Is your feature request related to a problem? Please describe.**
Recently NTHU decided to turn off the feature of searching classmates due to "personal data protection" reasons. However there is still a lot of people that used this feature for contacting and forming groups within classes. Thus we should build up our own

**Describe the solution you'd like**
Needs to have KYC(know your customer) by logging in and verifying their details. Then they must agree to share their details to the specific class, only then they can see which students are in the class. Preferably this should be done through the timetable page.

**Comment by ImJustChew** [comment]
A problem would be how to prevent information misuse. Someone would be able to just register a course, access everyone's details and leave the course.

**Comment by Joshimello** [comment]
Suggestions
1. Embrace open info and allow all to see by default, but have the settings to allow yourself to be hidden from list.
2. Lock in view of classmates after course selection period to those who still have it selected.

**Comment by ImJustChew** [comment]
But I'm assuming they have to be logged in. Once logged in, only you can see people who've consented to publicly show their details. But I'm unsure about locking in view cuz we don't actually know when someone will find out about our platform.
